gtk3/lib/gtk3/container.rb
changed, that it uses the add-method of Gtk::Container
=> add <<-alias for add-method

gtk3/sample/misc/aboutdialog2.rb, gtk3/sample/misc/alpha-demo.rb
I have just updated the copyright and the version check because it looks like that the show Class method doesn't exist. I will create an issue for this
=> update copyright and version check

gtk3/sample/misc/assistant.rb
use hash parameters form and update copyright
=> update to gtk3 api

gtk3/lib/gtk3/combo-box.rb, gtk3/lib/gtk3/loader.rb, gtk3/test/test_gtk_combo_box.rb
This is for the issue #340 
I think that the combo-box.rb could be modified/improved. I the entry parameter(line 21 of this file) is  a boolean false by default.
I am not an experienced dev sorry. I would appreciate any advices.
=> add hash arguments for Gtk::ComboBox.new

gtk3/sample/misc/textbuffer_serialize.rb
There are a lot of changes between the previous api and the current so I had to modify somehow the script. I think that it is close to the previous one. Let me know what you want me to rewritte.
=> update to gtk3 api  and update copyright in textbuffer_serialize.rb

gtk3/lib/gtk3/deprecated.rb
I hope this is the right way to do this
=> add deprecated messages for Gtk::ColorSelection 

gtk3/sample/misc/textbuffer_serialize.rb
add missing stuff for Gtk::TextBuffer
=> Gtk3 sample misc text buffer serialize

gtk3/lib/gtk3/loader.rb, gtk3/lib/gtk3/toggle-button.rb, gtk3/test/test-gtk-toggle-button.rb
I didn't find a way to test the use of mnemonic in the test file. Any ideas?
=> use hash argument for Gtk::ToggleButton#new

gtk3/sample/misc/button.rb
I have replaced deprecated table by a grid
=> update to gtk3 api  and update copyright in button.rb

gtk3/sample/misc/application.rb
Gtk::Application and Gtk::ApplicationWindow example.
=> add a new sample illustrating the use of Gtk::Application

gtk3/sample/misc/application.rb
Just a fix to illustrate the use of the flags
=> use :flags_none instead of its value

gtk3/sample/misc/drawing.rb
I have to rewrite all based on the C example.
I have done an issue (#403) for a problem with Gdk::EventMask constants
=> update drawing.rb to Gtk+3 api

gtk3/sample/misc/misc_button.rb
I have rewrite this initial line : Gtk::Window.new.add(box).set_default_size(200, 100).show_all in multiple lines for a better readability even if I have seen that now this kind of statement works.
=> Update to Gtk3 api and update copyright in misc_button.rb

gtk3/sample/misc/dnd.rb
I have added those lines : 
```ruby
puts selection_data.data[0].pack("C#{data_len}")
puts selection_data.text
```
Because that was not obvious. If you prefer that I remove all the lines I have added and that I stay closer to the initial script just tell me and I will do the modifications.
=> Update to Gtk3 api, update Copyright and fix style issue in dnd.rb

gtk3/lib/gtk3/loader.rb
I tryed to do like this 8e23852b2c2d7349f85d8b8a70d1a1fff5d36424. I am not sure on how to create tests for this
=> Remove list_ from Gtk::Widget#list_style_properties

gtk3/sample/misc/list_store_usage.rb
I don't know if you could find this usefull but I have written this very simple script in order to see how the Gtk::ListStore methods works so I share.
=> Add a simple script show the API of the Gtk::ListStore

gtk3/sample/misc/combobox_from_cellrender.rb
This is an example of a combobox in which the boolean value of the model are represented by a Gtk::CellRenderToggle
=> Add example of combobox

glib2/README.md
=> Modify README to README.md

vte3/lib/vte3/terminal.rb
Sorry kou but I didn't find a way to create a test. I have tried to use GLib::Tiemout , Vte::Terminal#cursor_position with the "cursor-moved" signal but wihtout success. I am stuck.
=> Vte3 terminal feed child

gtk3/sample/tutorial/exampleapp5/app-menu.ui, gtk3/sample/tutorial/exampleapp5/exampleapp.gresource.xml, gtk3/sample/tutorial/exampleapp5/exampleapp.rb, gtk3/sample/tutorial/exampleapp5/org.gtk.exampleapp.gschema.xml, gtk3/sample/tutorial/exampleapp5/window.ui, gtk3/sample/tutorial/exampleapp6/app-menu.ui, gtk3/sample/tutorial/exampleapp6/exampleapp.gresource.xml, gtk3/sample/tutorial/exampleapp6/exampleapp.rb, gtk3/sample/tutorial/exampleapp6/org.gtk.exampleapp.gschema.xml, gtk3/sample/tutorial/exampleapp6/prefs.ui, gtk3/sample/tutorial/exampleapp6/window.ui
I have some warnings with those scripts (those are just warnings but they bother me):
```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb: line 551
Gtk-DEBUG **:Connecting to session manager
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb: line 551
Gtk-WARNING **:Duplicate child name in GtkStack: exampleapp.rb
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb: line 551
Gtk-WARNING **:Duplicate child name in GtkStack: exampleapp.rb
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb: line 551
Gtk-WARNING **:Duplicate child name in GtkStack: exampleapp.rb …
```
=> Gtk3 sample tutorial exampleapp5 and 6

gtk3/sample/tutorial/README.md
@kou I need your help in the part "link the template to a custom class widget".
I do understand the principles of GType and or singleton methods and eigenclass in Ruby. But I miss something (or a lot of things) in order to get the big picture and explain it clearly.
*    why do we need to use type_register (create a new GType)
*    why do we overwritte the init method in the eigenclass
*    when this method will be called after that 
*    why the set_template is called in the  init method (why not in the initialize method)
*    Is it more related to GLib:Object ? where can I found more informations on this.
If you have some links / good resources on GType, GObject, GObjectIntrospection that are related to this, I am interested.
=> Add populating the window part

gtk3/sample/tutorial/exampleapp10/app-menu.ui, gtk3/sample/tutorial/exampleapp10/exampleapp.gresource.xml, gtk3/sample/tutorial/exampleapp10/exampleapp.rb, gtk3/sample/tutorial/exampleapp10/gears-menu.ui, gtk3/sample/tutorial/exampleapp10/org.gtk.exampleapp.gschema.xml, gtk3/sample/tutorial/exampleapp10/prefs.ui, gtk3/sample/tutorial/exampleapp10/window.ui
=> Add exampleapp10

atk/lib/atk.rb, atk/test/test-version.rb
I hope it is close to what you want. 
I had to remove the test on `vendor_dir.exist?` otherwise I was not able to run the test on my system (Arch Linux x86_64)
=> Atk version or later method

clutter-gstreamer/lib/clutter-gst.rb, clutter-gstreamer/test/test-clutter-gst-version.rb
=> Clutter gstreamer version or later

gio2/lib/gio2.rb, gio2/lib/gio2/loader.rb, gio2/test/test-version.rb
=> Gio2 version or later

gstreamer/lib/gst.rb, gstreamer/lib/gst/version.rb, gstreamer/test/test-version.rb
ref #308 
I have added a Gst::Version::NANO constant but I let the Gst::Version::STRING with the same form as in the other module ie: MAJOR . MINOR . MICRO.
=> Gstreamer version or later

gtk2/lib/gtk2/base.rb, gtk2/test/test_gtk_version.rb
=> Gtk2 version or later

pango/lib/pango.rb, pango/test/test-version.rb
=> Pango version or later

poppler/lib/poppler.rb, poppler/test/test-version.rb
=> Poppler version or later

rsvg2/lib/rsvg2.rb, rsvg2/test/test-version.rb
=> Rsvg2 version or later

gtk3/sample/gtk-demo/main.rb
Ok so let start with this.
Just the basic skeleton for the main file and an naive implementation for the command line management. I am waiting for advices.
=> Gtk3 sample gtk demo main rb

gtk3/sample/gtk-demo/main.rb, gtk3/sample/gtk-demo/main.ui
I create this pull request because the next step should be to list the demos and populate the model of the treeview
=> Gtk3 sample gtk demo main rb run application

gtk3/sample/gtk-demo/log, gtk3/sample/gtk-demo/main.rb, gtk3/sample/gtk-demo/test_mod.rb
After that it will remain to implement:
*    auto_quit callback
*    the callback for treeview selection-changed signal
*    activate_about callback
*    activate_quit callback
*    selection_cb callback
*    file loading function
*    basic syntax highlighting
=> Gtk3 sample gtk demo main rb run demo for module

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/scale.rb
=> Gtk3 sample gtk demo scale rb

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/revealer.rb
Sorry for the name of the branch (it should be gtk3_sample_gtk_demo_revealer_rb instead of gtk3_sample_gtk_demo_entry_revealer_rb)
=> Add revealer demo

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/colorsel.rb
In the line 52, I added `da.queue_draw` because when I tested the demo, I noticed this each time:
*    launch the demo
*    change the color --> nothing happens in the drawing area
*    change the color --> drawing area with a new background color
With this I am sure that the change are effective.
=> Update colorsel demo

gtk3/ext/gtk3/rb-gtk3.c
This is a tested working TreeSelectionFunc implementation for Gtk3.  I have not included a test case as I'm not sure the best way to test this without opening a window.
=> Add support for GtkTreeSelection

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/css_pixbufs.rb
Please don't merge right now have a look at this issue #645
remains:
*    fix pb with css
*    update TODO file
=> Update css_pixbufs demo

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/iconview_edit.rb
=> Gtk3 sample gtk demo iconview edit rb

glib2/ext/glib2/rbglib.c, glib2/ext/glib2/rbglib_matchinfo.c, glib2/ext/glib2/rbglib_regex.c, glib2/ext/glib2/rbgprivate.h, glib2/test/test-regex.rb
*    `GLib::MatchInfo` class
*    `GLib::MatchInfo#string`
*    `GLib::MatchInfo#regex`
*    `GLib::MatchInfo#matches?`
*    `GLib::Regex#match`
*    and tests
=> Glib2 regex match

glib2/ext/glib2/rbglib_regex.c, glib2/test/test-regex.rb
=> Glib2 regex capture count

gtk3/test/test-gtk-tree-iter.rb
Before working on #682 I think we should finish and improve the tests
=> Improve and finish tests for Gtk::TreeIter

gtk3/lib/gtk3/loader.rb
For the issue #683. 
@kou I hope this is the best to do it.
=> Add Gtk::TreePath#next! , prev!, up! and down! methods

gtk3/lib/gtk3/tree-iter.rb, gtk3/test/test-gtk-tree-iter.rb
=> Gtk3 lib tree iter first child

gtk3/test/test-gtk-tree-path.rb
=> Add tests for Gtk::TreePath#next!, #prev!, #up!, and #down! methods

gtk3/sample/misc/app-menu.ui, gtk3/sample/misc/button-menu.ui, gtk3/sample/misc/menus_from_resources.gresource.xml, gtk3/sample/misc/menus_from_resources.rb, gtk3/sample/misc/toolbar-menu.ui
Add example that shows 3 types of menus and actions generated form UI files and gresources
=> Add menus_from_resources.rb script and its UI files

gtk3/sample/gtk-demo/main.rb
Enable the possibility to run the currently selected demo in the treeview via the run button
=> Link the run button to an action

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/assistant.rb
=> Gtk3 sample gtk demo assistant rb

NEWS
I have added a global section because I didn't know where those changes should be added.
It takes me a lot of time. Maybe we should do this more frequently?
=> Finish the NEWS sumup

glib2/ext/glib2/rbglib_matchinfo.c, glib2/test/test-match-info.rb
=> Glib2 match info expand references

README.md
Oups supported and not supproted .
=> Update the ruby versions supproted

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/demo.gresource.xml, gtk3/sample/gtk-demo/main.ui
I have updated/checked the main.rb and its interface files.
=> Gtk3 sample gtk demo main rb update 3 20

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/font-features.ui, gtk3/sample/gtk-demo/font_features.rb
All the demos that were updated in the gtk 3.19 version are now updated to the 3.20. if needed.
=> Finish update 3.20 for the demos in 3.19 version

pango/ext/pango/rbpangoattrlist.c
I was looking how you handled the callbacks in pango and I have found this macro inversion.
=> Fix error with MACRO usage

gtk3/sample/misc/bindings.rb
Detlef reported having issue with the Css that didn't work recently in ruby-gnome2-devel-en.
This file is the only one that needed to be updated in all the demo/samples.
I need to check the gtk tutorial. I hope be able to do it in the next days.
=> Gtk3 sample misc bindings rb update css

gtk3/test/test-pango-context.rb, pango/ext/pango/rbpangocontext.c
Sorry for the delay,
I have created a new pull request. It is cleaner.
=> Pango ext pango context set shape renderer

gtk3/sample/tutorial/README.md
Was it a typo or did the method change?  I dunno. It works now.
=> The size ssting method was wrong

gtk3/sample/gtk-demo/main.rb
=> Fix typo at gtk-demo

gtk3/lib/gtk3/deprecated.rb, gtk3/lib/gtk3/image.rb, gtk3/lib/gtk3/text-buffer.rb
=> Gtk3 lib gdk pixbuf new form

NEWS
From : 
git log --decorate --stat --reverse --after="2016-04-03"
There are some parts that you should look at (at the very beginning).
=> Start updating NEWS file

gobject-introspection/ext/gobject-introspection/rb-gi-argument.c
For the crash when `GdkPixbuf::Pixbuf#formats` is called #839
=> Support gslist of struture values as return value

gtk3/sample/misc/dnd.rb
=> Gtk3 selection data api changes

glib2/ext/glib2/rbgobj_type.c
Related to #845.
ref: https://bugs.ruby-lang.org/issues/12005
=> glib2: support Ruby 2.4 Integer unification

gtk3/sample/gtk-demo/main.rb
=> Gtk3 sample gtk demo main rb load demo as class

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/drawingarea.rb
@kou, could you check this demo at lines 165-170. I can not find which way is the better in order to define the events we want to catch.
It looks like in the demo, the da is not able to catch motion events.
Thx.
=> Gtk3 sample gtk demo drawingarea rb

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/listbox.rb
I would like to point out that the demo takes some times to load. And that it doesn't work exactly like the C demo, the extra_buttons_box in each row is shown even if the row is not selected when the demo starts.
=> Gtk3 sample gtk demo listbox rb

glib2/ext/glib2/rbglib_iochannel.c, gtk2/ext/gtk2/rbgtkcontainer.c, gtk3-no-gi/ext/gtk3/rbgtk-container.c
=> fix error messages typo

NEWS
Here is the NEWS file updated. The last commit I used is 55b24df4bbe128f55cda0997f91e7903a9c06f98.
=> Update NEWS from 2016-08-12 to 2016-11-12

.travis.yml
Ruby 2.4.0 had been released this year too. :santa: :christmas_tree:
=> Tweak for Ruby version in Travis settings

gtk3/lib/gtk3/dialog.rb
Support for ResponseType parameter.
=> Fix get_widget_for_response method.

gtk3/sample/gtk-demo/TODO
=> Update TODO for gtk-demo

webkit2-gtk/lib/webkit2-gtk.rb, webkit2-gtk/lib/webkit2-gtk/web_view.rb, webkit2-gtk/test/test-webkit2-gtk-webview.rb
This makes all `new_with_<something>` constructors available for WebView, similar to Pixbuf.
=> Make WebView constructors available

gtk3/sample/gtk-demo/main.rb
=> main.rb : use Pango constants names from new API

gtk3/sample/gtk-demo/textview.rb
It remains two constants to update but they are not implemented (see #1048 )
=> Update to new api of Pango

cairo-gobject/test/run-test.rb, glib2/test/run-test.rb, gobject-introspection/test/run-test.rb
this fix use other tests as reference.
=> check existence of Makefile before running make

poppler/README.md
=> Fix bad instruction for installation

poppler/test/test-annotation.rb, poppler/test/test_color.rb, poppler/test/test_constants.rb, poppler/test/test_document.rb, poppler/test/test_page.rb
=> drop codes for poppler version < 0.15.0

poppler/lib/poppler/page.rb, poppler/test/test-page.rb
=> Poppler lib page find text

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/fishbowl.rb, gtk3/sample/gtk-demo/fishbowl.ui
It remains a little issue with the toggle button., the prevent changes toggle button should not appears at first.
=> Gtk3 sample gtk demo fishbowl rb

gtk3/sample/gtk-demo/TODO, gtk3/sample/gtk-demo/toolpalette.rb
another one. (it remains 5 to do)
=> Gtk3 sample gtk demo toolpalette rb

gtk3/README.md
- add tutorials, examples part
- add link to external tutorial cc @iridakos
- update copyright
=> Improve gtk3 readme

gtk4/sample/grid_packing.rb, gtk4/sample/hello_world.rb, gtk4/sample/utils.rb
I added a utils.rb file in order to share a function to load the Gtk4/Gdk4 libs while there are no gems for them.
=> Gtk4 sample utils

gdk_pixbuf2/lib/gdk_pixbuf2/pixbuf.rb
=> Gdk pixbuf2 composite

gtk4/lib/gtk4/loader.rb, gtk4/lib/gtk4/message-dialog.rb, gtk4/sample/action-namespace.rb, gtk4/test/test-gtk-message-dialog.rb
=> Gtk4 sample action namespace rb

gio2/lib/gio2/settings.rb, gio2/test/test-settings.rb
=> Gio2 settings new

glib2/Rakefile, glib2/glib2.gemspec, glib2/lib/gnome2/rake/package-task.rb
=> Glib2 static gem spec

cairo-gobject/Rakefile, cairo-gobject/cairo-gobject.gemspec, cairo-gobject/version.rb
=> Cairo gobject static gem spec

gobject-introspection/Rakefile, gobject-introspection/gobject-introspection.gemspec, gobject-introspection/version.rb
=> GObject-introspection: use static gemspec file

gtksourceview3/Rakefile, gtksourceview3/gtksourceview3.gemspec
=> gtksourceview3 : add static gemspec

gdk_pixbuf2/README.md
=> fix GdkPixbuf2 README

README.md, rsvg2/README.md, rsvg2/rsvg2.gemspec
fix typo
https://github.com/ruby-gnome2/ruby-gnome2/issues/1252
=> use RSVG instead of Rsvg

gtk3/sample/misc/aboutdialog.rb
Fixed an error when clicking the link.
=> Gtk example misc aboutdialog

gtk3/sample/misc/calendar.rb
1. remove "Gtk::CalendarDisplayOptions::NO_MONTH_CHANGE" so that you can change month.
2. use `year`, `month`, `day` properties in GtkCalendar.
=> update gtk3 sample/misc calendar

gtk3/sample/misc/aboutdialog.rb
=> gtk3: fix aboutdialog example

gtk3/sample/misc/builder.rb
=> gtk3: fix builder example

gtk3/sample/misc/button2.rb
* Remove needless spaces
* Add a space
=> gtk3: fix button2 example

gtk3/sample/misc/calendar.rb
=> gtk3: fix calendar example

gtk3/sample/misc/dndtreeview.rb
* Add appropriate column names
* before
* after
=> gtk3: improve dndtreeview example

gtk3/sample/misc/drawing.rb
* Remove a needless space
* Ruby-Style conditional branching
=> gtk3: fix drawing example

gtk3/sample/misc/linkbutton.rb
=> gtk3: fix linkbutton example

gtk3/sample/misc/misc-button.rb
* Use a symbol instead of a constant
=> gtk3: improve misc-button example

gtk3/README.md
=> gtk3: update gtk3 readme

vte3/README.md
=> vte3: update README

gdk_pixbuf2/README.md
I rewrote the readme.
Please check requirements
=> gdk_pixbuf2: update readme

gdk_pixbuf2/sample/flip.rb
Additional typo fix
:confused:
=> gdk_pixbuf2: fix a typo in flip example

gegl/dependency-check/Rakefile, webkit2-gtk/dependency-check/Rakefile
* Fix #1350
* Fix typo in gegl
=> Fix typos related to package_id

webkit2-gtk/README.md
=> webkit2-gtk: update README

gtk3/sample/misc/scalebutton.rb
* Use symbols instead of constants
=> gtk3: improve scalebutton example

gtk3/sample/misc/stock.rb
* Use `cycle` method instead of counter
* Always place buttons at the bottom of the window so you can click continuously
=> gtk3: improve stock example

gtksourceview4/sample/test.rb
* Create sample directory
* Add a new sample based on the sourceview2 sample
* screenshot
=> gtksourceview4: add a example

atk/README.md, atk/atk.gemspec, atk/test/run-test.rb
* Update copyright year in README
* Align lines in the gemspec file.
```
ruby test/run-test.rb 
```
```
Started
.....
Finished in 0.000852496 seconds.
--------------------------------------------------------------------------------
5 tests, 8 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------
5865.13 tests/s, 9384.21 assertions/s
```
=> atk: ruby_gnome2_base -> ruby_gnome_base

gdk3/test/run-test.rb
```
gdk3$ ruby test/run-test.rb
```
```
Started
...........................................................................................................
............................................................................
(run-test.rb:6922): Gdk-WARNING **: 22:15:26.670: losing last reference to undestroyed window
(run-test.rb:6922): Gdk-WARNING **: 22:15:26.670: losing last reference to undestroyed window
(run-test.rb:6922): Gdk-WARNING **: 22:15:26.670: losing last reference to undestroyed window
(run-test.rb:6922): Gdk-WARNING **: 22:15:26.671: losing last reference to undestroyed window
(run-test.rb:6922): Gdk-WARNING **: 22:15:26.671: losing last reference to undestroyed window
(run-test.rb:6922): …
```
=> gdk3: ruby_gnome2_base -> ruby_gnome_base

gdk_pixbuf2/test/run-test.rb
```
gdk_pixbuf2$ ruby test/run-test.rb 
```
```
Started
..............................
Finished in 0.132325503 seconds.
-----------------------------------------------------------------------------------------------------------
30 tests, 55 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-----------------------------------------------------------------------------------------------------------
226.71 tests/s, 415.64 assertions/s
```
=> gdk_pixbuf: ruby_gnome2_base -> ruby_gnome_base

gegl/test/run-test.rb
```
gegl$ ruby test/run-test.rb 
```
```
Started
.....
Finished in 0.118401874 seconds.
-----------------------------------------------------------------------------------------------------------
5 tests, 5 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-----------------------------------------------------------------------------------------------------------
42.23 tests/s, 42.23 assertions/s
```
=> gegl: ruby_gnome2_base -> ruby_gnome_base

gio2/test/run-test.rb
* Change `ruby_gnome2_base` to  `ruby_gnome2_base`
```
gio2$ ruby test/run-test.rb 
```
```
Started
...........................................................................
Finished in 0.688617146 seconds.
-----------------------------------------------------------------------------------------------------------
75 tests, 94 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-----------------------------------------------------------------------------------------------------------
108.91 tests/s, 136.51 assertions/s
```
=> gio2: ruby_gnome2_base -> ruby_gnome_base

gobject-introspection/test/run-test.rb
```
gobject-introspection$ ruby test/run-test.rb 
```
```
Started
...............................................................................
...............................................
Finished in 0.018208291 seconds.
-------------------------------------------------------------------------------
126 tests, 126 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------
6919.92 tests/s, 6919.92 assertions/s
```
=> gi: ruby_gnome2_base -> ruby_gnome_base

gsf/test/run-test.rb
```
gsf$ ruby test/run-test.rb 
```
```
Started
.
Finished in 0.000873904 seconds.
-------------------------------------------------------------------------------
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------
1144.29 tests/s, 1144.29 assertions/s
```
=> gsf: ruby_gnome2_base -> ruby_gnome_base

gstreamer/test/run-test.rb
```
gstreamer$ ruby test/run-test.rb 
```
```
Started
.............
Finished in 0.008356026 seconds.
-------------------------------------------------------------------------------
13 tests, 13 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------
1555.76 tests/s, 1555.76 assertions/s
```
=> gstreamer: ruby_gnome2_base -> ruby_gnome_base

gtksourceview3/test/run-test.rb
```
gtksourceview3$ ruby test/run-test.rb
```
```
Started
............
Finished in 0.648059631 seconds.
12 tests, 14 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
18.52 tests/s, 21.60 assertions/s
```
=> gtksourceview3: ruby_gnome2_base -> ruby_gnome_base

gtksourceview4/test/run-test.rb
```
gtksourceview4$ ruby test/run-test.rb 
```
```
Started
............
Finished in 0.599314223 seconds.
12 tests, 14 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
20.02 tests/s, 23.36 assertions/s
```
=> gtksourceview4: ruby_gnome2_base -> ruby_gnome_base

pango/test/run-test.rb
```
pango$ ruby test/run-test.rb
```
```
Started
..............................................................
Finished in 0.15463356 seconds.
62 tests, 79 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
400.95 tests/s, 510.89 assertions/s
```
=> pango: ruby_gnome2_base -> ruby_gnome_base

rsvg2/test/run-test.rb
```
rsvg2$ ruby test/run-test.rb
```
```
Started
.......
Finished in 3.7341732 seconds.
7 tests, 7 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
1.87 tests/s, 1.87 assertions/s
```
=> rsvg2 ruby_gnome2_base -> ruby_gnome_base

vte3/test/run-test.rb
```
vte3$ ruby test/run-test.rb 
```
```
Started
.............................
Finished in 0.035574305 seconds.
29 tests, 24 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
815.20 tests/s, 674.64 assertions/s
```
=> vte3: ruby_gnome2_base -> ruby_gnome_base

wnck3/test/run-test.rb
```
wnck3$ ruby test/run-test.rb 
```
```
Started
.....
Finished in 0.018398529 seconds.
5 tests, 5 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
271.76 tests/s, 271.76 assertions/s
```
=> wnck3: ruby_gnome2_base -> ruby_gnome_base

README.md
Hello.
This pull request is intended to make the README easier to read when viewed in a web browser.
Also, I think this change will make it easier to maintain the package list.
Thank you.
=> Convert the packages lists into tables in README

README.md, gtk3/README.md, gtk4/README.md
Update gtk3/gtk4 sample directory refs in READMEs
=> Update gtk3/gtk4 sample directory refs in READMEs

.github/workflows/doc.yml, Gemfile
Draft pull request for discussion.
I do not expect this to be merged as is, but something is better than nothing.
@kou Please comment.
=> Kojix2 doc challenge

gtk4/sample/examples/builder.rb, gtk4/sample/examples/builder.ui
* https://gitlab.gnome.org/GNOME/gtk/blob/main/examples/builder.c
* https://gitlab.gnome.org/GNOME/gtk/blob/main/examples/builder.ui
=> gtk4: fix builder.rb sample

gtk4/sample/examples/application5/Rakefile, gtk4/sample/examples/application5/exampleapp.rb, gtk4/sample/examples/application6/README.md, gtk4/sample/examples/application6/Rakefile, gtk4/sample/examples/application6/exampleapp.rb, gtk4/sample/examples/application6/org.gtk.exampleapp.gschema.xml
Add gtk4/sample/examples/application6 diretory
=> gtk4: Add sample/examples/application6

gtk4/sample/examples/application5/exampleapp.rb, gtk4/sample/examples/application6/exampleapp.rb, gtk4/sample/examples/application7/README.md, gtk4/sample/examples/application7/Rakefile, gtk4/sample/examples/application7/exampleapp.rb, gtk4/sample/examples/application7/org.gtk.exampleapp.gschema.xml
Add gtk4/sample/examples/application7
=> gtk4: Add sample/examples/application7

gtk4/sample/examples/application3/exampleapp.rb, gtk4/sample/examples/application4/exampleapp.rb, gtk4/sample/examples/application5/exampleapp.rb, gtk4/sample/examples/application6/exampleapp.rb, gtk4/sample/examples/application7/README.md, gtk4/sample/examples/application7/exampleapp.rb, gtk4/sample/examples/application8/README.md, gtk4/sample/examples/application8/Rakefile, gtk4/sample/examples/application8/exampleapp.rb, gtk4/sample/examples/application8/org.gtk.exampleapp.gschema.xml
Add gtk4/sample/examples/application8
=> gtk4: Add sample/examples/application8

gtk4/sample/examples/application7/exampleapp.rb, gtk4/sample/examples/application9/README.md, gtk4/sample/examples/application9/Rakefile, gtk4/sample/examples/application9/exampleapp.rb, gtk4/sample/examples/application9/org.gtk.exampleapp.gschema.xml
Add gtk4/sample/examples/application9
=> gtk4: Add sample/examples/application9

gtk4/sample/examples/menubar.rb
=> gtk4: Add sample/examples/menubar.rb

gtk4/sample/examples/menubar.rb
https://github.com/ruby-gnome/ruby-gnome/issues/1581#issuecomment-1778109286
=> gtk4: fix the license of gtk4/sample/examples/menubar.rb

gdk3/test/test-gdk-keyval.rb, gdk4/test/test-gdk-keyval.rb
Fixing typos with [typos-cli](https://github.com/crate-ci/typos)
=> Fix a typo in gdk

glib2/ext/glib2/rbgobj_object.c, glib2/ext/glib2/rbgutil.h, glib2/lib/glib2.rb, glib2/sample/timer.rb, glib2/test/test-regex.rb
Fixing typos with [typos-cli](https://github.com/crate-ci/typos)
=> glib2: fix typos

gobject-introspection/ext/gobject-introspection/rb-gi-struct-info.c, gobject-introspection/lib/gobject-introspection/loader.rb, gobject-introspection/test/test-loader.rb
Typo correction with [typos-cli](https://github.com/crate-ci/typos)
=> gi: fix typos

glib2/sample/bookmarkfile.rb
=> glib2: Fix typo

glib2/ext/glib2/rbgobj_value.c
=> glib2: add support for GValue<TypeInstance> to Ruby

glib2/ext/glib2/rbgobj_value.c
=> glib2: add support for Ruby to GValue<TypeInstance>

gobject-introspection/ext/gobject-introspection/rb-gi-arguments.c
=> gi: use `ref`/`unref` for `GTypeInstance`
