ruby-gnome/ruby-gnome

- gtk3/lib/gtk3/calendar.rb
- gtk3/lib/gtk3/loader.rb
GTK+ 2 and GTK+ 3 are use 0-11 as a range of calendar month.
But Ruby/GTK2 is uses 1-12 as a range of calendar month. I
think we should use 1-12 as a range of calendar month.
What do you think?
See: https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gtk2/ext/gtk2/rbgtkcalendar.c#L41
> gtk3: use 1-12 as a range of calendar month

- gtk3/lib/gtk3/combo-box-text.rb
- gtk3/lib/gtk3/loader.rb
- gtk3/test/test_gtk_combo_box_text.rb
Allow user to create a Gtk::ComboBoxText with entry using :entry => true
> handle initialize with entry for Gtk::ComboBoxText

- gtk3/lib/gtk3/font-chooser-dialog.rb
- gtk3/lib/gtk3/loader.rb
- gtk3/test/test_gtk_font_chooser_dialog.rb
In order to be consistant with the other dialogs
> Gtk::FontChooserDialog with hash arguments

- gtk3/sample/misc/linkbutton.rb
I had to remove the part Gtk::LinkButton.set_uri_hook because it was deprecated.
> update to new api and update copyright linkbutton.rb

- gtk3/lib/gtk3/loader.rb
I use `rubyish_method_name` to define `#each_all` from `#forall`.
Actually, using `rubyish_method_name` is Ruby-GNOME2 way.
It was beyond my thought when implementing my first patch.
> gtk3 container: use rubyish_method_name to define #each_all from #forall

- gtk3/sample/misc/togglebutton.rb
It was because of this sample that I was reluctant to use the symbol :use_underline and that I used :mnemonic. On my system when I launch it, the button with :use_underline => true is not underlined but the mnemonic works.
regards
> update to gtk3 api  and update copyright in togglebutton.rb

- gtk3/lib/gtk3/loader.rb
- gtk3/lib/gtk3/target-entry.rb
- gtk3/lib/gtk3/widget.rb
I don't know if it is the rigth way to do this. I just imited you from a recent commit.
This solve a pb I had witht the script sample/misc/dnd.rb
```ruby
drag_dest_set(Gtk::DestDefaults::MOTION |
Gtk::DestDefaults::HIGHLIGHT,
[["test", Gtk::TargetFlags::SAME_APP, 12345]],
Gdk::DragAction::COPY |
Gdk::DragAction::MOVE)
```
The line in comments above does work with my patch
> add support for Gtk::TargetFlags symbols for Gtk::Widget#drag_dest_set

- glib2/ext/glib2/rbglib_fileutils.c
- glib2/test/test_file_utils.rb
fixes #413
Because following RangeError exception is thrown when GLib.format_size(1000 * 1000 * 1000 * 5):
```log
Error: test_5gb(TestGLibFileUtils::#format_size)
: RangeError: integer 5000000000 too big to convert to `unsigned int'
ruby-gnome2/glib2/test/test_file_utils.rb:34:in
`format_size'
ruby-gnome2/glib2/test/test_file_utils.rb:34:in
`test_5gb'
31:     end
32:
33:     def test_5gb
=> 34:       assert_equal("5.0 GB", GLib.format_size(1000 * 1000 * 1000 * 5))
35:     end
36:
37:     sub_test_case "flags" do
```
>     glib2: Use NUM2ULONG instead of NUM2UINT in GLib.format_size

- gtk3/ext/gtk3/rb-gtk3-container.c
- gtk3/lib/gtk3/container.rb
- gtk3/sample/misc/template.gresource.xml
- gtk3/sample/misc/template.ui
- gtk3/sample/misc/template_from_resource.rb
- gtk3/test/fixture/Rakefile
- gtk3/test/fixture/template.gresource.xml
- gtk3/test/fixture/template.ui
- gtk3/test/test-gtk-container.rb
This patch tries to add support for GTK widget template.  With this, users don't need to manually call ```builder.get_object()```.
The implementation is similar to the one in Gjs:
https://bugzilla.gnome.org/show_bug.cgi?id=700347
At the moment, I don't request merging this to the upstream, but would like to hear opinions on the desired Ruby interface of the widget template support, e.g., automatic mapping between widgets and accessors.
Comments would be appreciated.
> gtk3: add support for widget template

- gtk3/lib/gtk3/list-store.rb
Setup the model of the resulting `Gtk::TreeIter`  returned by `Gtk::ListStore#prepend`
Fix this kind of pb:
```ruby
model = Gtk::ListStore.new(TrueClass, String)
model.prepend.set_values([true, "item5"])
```
that returns:
```
/home/cedlemo/.gem/ruby/2.2.0/gems/gtk3-2.2.6/lib/gtk3/tree-iter.rb:38:in `set_values': undefined method `set_values' for nil:NilClass (NoMethodError)
```
> Setup the model of the returned Gtk::TreeIter

- gtk3/sample/misc/menu.rb
I have replaced the `Gtk::OptionMenu.new` by a `Gtk::ComboBox` (based on a `Gtk::RenderCellToggle`) like specified in the deprecated message.
> Update to Gtk3 api, update Copyright and fix style issue in menu.rb

- gtk3/sample/misc/gtkglarea1.rb
Here is the first example of the Gtk::GLArea. I plan to do 2 or 3 more examples (for fun).
It could be great to put a reference of the OpenGL bindings we support in th README.
> Add sample script for the Gtk::GLArea widget

- atk/test/atk-test-utils.rb
- cairo-gobject/test/cairo-gobject-test-utils.rb
- clutter-gstreamer/test/clutter-gstreamer-test-utils.rb
- clutter-gtk/test/clutter-gtk-test-utils.rb
- clutter/test/clutter-test-utils.rb
- gdk3-no-gi/test/gdk-test-utils.rb
- gdk3/test/gdk-test-utils.rb
- gio2/test/gio2-test-utils.rb
- gobject-introspection/test/gobject-introspection-test-utils.rb
- rsvg2/test/rsvg2-test-utils.rb
- vte3/test/vte3-test-utils.rb
- webkit-gtk/test/webkit-gtk-test-utils.rb
- webkit-gtk2/test/webkit-gtk-test-utils.rb
All references have been found with:
find ./ -type f -name "*.rb"| xargs grep -l "unit/notify"
> Remove dependancy to test-unit-notify gem

- Gemfile
- cairo-gobject/Rakefile
- clutter-gstreamer/Rakefile
- clutter-gtk/Rakefile
- clutter/Rakefile
- webkit-gtk/Rakefile
- webkit-gtk2/Rakefile
- webkit2-gtk/Rakefile
Sorry but when I checked for the test-unit-notify I just only search them in `*.rb` files
here is the command that returns me the files that remains:
```
find ./ -type f | xargs grep -l "test-unit-notify"
```
> Remove reference to test-unit-notify in some Rakefile

- gtk3/ext/gtk3/extconf.rb
Testing this was way harder than changing the code. I had to set up an Arch VM with a bunch of gui packages removed, to get Gtk3 to be removed.
I think it will be rare that users don't already have Gtk3 installed, but at least I have seen this change work.
> Add Arch Linux support for auto install of native Gtk3 package.

- gtk3/sample/gtk-demo/main.rb
There is an important fix in this pull request, when I simplified the code, the children where not well registred.
The list_demos method works when you launch:
./main.rb --list
> Gtk3 sample gtk demo main rb list demos method

- gtk3/sample/gtk-demo/main.rb
- gtk3/sample/gtk-demo/test_mod.rb
The test_mod.rb is only for the test and implementation purpose. It will be removed later (It just help me to focus on the way to load the demo files and code.
> add a test module and implement the use of test_mod.rb

- gtk3/ext/gtk3/rb-gtk3-tree-view.c
"rbgobj_gc_mark_instance" has to be called for the GtkTreeSelection associated with tree_view.
> "rbgobj_gc_mark_instance" has to be called for the GtkTreeSelection

- gtk3/lib/gtk3/widget.rb
- gtk3/test/test-gtk-widget.rb
`Gtk::Widget#translate_coordinates` returns an array like this [x, y] if it works or nil.
> Make Gtk::Widget#translate_coordinates more rubyish

- glib2/ext/glib2/rbglib-variant.c
This fixes the following error:
irb(main):001:0> require 'glib2'
=> true
irb(main):002:0> GLib::Variant.new(333222111000)
RangeError: integer 333222111000 too big to convert to `int'
from (irb):2:in `initialize'
from (irb):2:in `new'
from (irb):2
from /usr/bin/irb:11:in `<main>'
> glib2: fix handling of 64 bits FIXNUM variant initialization

- gtk3/sample/misc/treestore.rb
It already exist a sample for the `Gtk::TreeView` that uses `Gtk::TreeStore` but this one is more focused on the `Gtk::TreeStore` and more simple.
> Add another example for Gtk::TreeStore

- glib2/ext/glib2/rbglib_matchinfo.c
- glib2/ext/glib2/rbglib_regex.c
- glib2/test/test-regex.rb
For the next pull requests: 
*    Should I have to implement `GLib::Regex.split` ( ``g_regex_split_simple`) in ruby using the method `GLib::Regex#split` like we did previously for `g_regex_match_simple`.
> Glib2 regex match all

- .travis.yml
- travis-before-script.sh
Related to https://github.com/ruby-gnome2/ruby-gnome2/issues/706.
* Start to use `dist: trusty`
* Install additional gi packages
* clutter
* clutter-gst
* gtkclutter
* webkit2
* Drop Ruby 2.0.0 support
* Use latest bundler
> travis: Try to use trusty beta image

- gtk3/sample/misc/icons-theme-viewer.rb
This example illustrate usage of `Gtk::IconTheme`, `Gtk::IconView` and `Gtk::Entry` and especially the secondary icon usage for the later.
> Add new example icons-theme-viewer.rb

- glib2/ext/glib2/rbglib_regex.c
- glib2/test/test-regex.rb
Maybe you won't agree with this. I wait for your advices.
It remains to do the `GLib::Regex#replace_eval` which will be tricky. Do you want that I do the simple methods for `GLib::MacthInfo` before it?
If you want that I do the `GLib::Regex#replace_eval ` in the next step you should look here https://github.com/cedlemo/ruby-gnome2/blob/f38f53d2032e0df457d88a2c2d1a4f2f65b2d9e9/glib2/ext/glib2/rbglib_regex.c#L212 and https://github.com/cedlemo/ruby-gnome2/blob/f38f53d2032e0df457d88a2c2d1a4f2f65b2d9e9/glib2/ext/glib2/rbglib_regex.c#L254 . This is How I plan to implement it. Tell me if there is something wrong with this.
> Glib2 regex check replacement

- glib2/ext/glib2/rbglib_matchinfo.c
- glib2/test/test-match-info.rb
Here is the how I visualize what I will do next:
*    `GLib::MatchInfo#expand_references` for `g_match_info_expand_references`
For the different fetch functions, I first thought to make just one method that would have an hash parameter like we did previously for `GLib::Regex#match` for exeample, but I didn't think that it would be a good idea.
*    `GLib::MatchInfo#fetch` for `g_match_info_fetch`
*    `GLib::MatchInfo#fetch_named` for `g_match_info_fetch_named`
*    `GLib::MatchInfo#fetch_pos` for `g_match_info_fetch_pos`
*    `GLib::MatchInfo#fetch_named_pos` for `g_match_info_fetch_named_pos`
*    `GLib::MatchInfo#next` for `g_match_info_next`
*    `GLib::MatchInfo#fetch_all` for `g_match_info_fetch_all`
Tell me if you see a better way to do this.
> Glib2 match info partial match

- glib2/ext/glib2/rbglib_matchinfo.c
- glib2/test/test-match-info.rb
2 more that remains:
*   `GLib::MatchInfor#next`
*   `GLib::MatchInfo#expand_references`
> Glib2 match info fetch all

- gtk3/sample/gtk-demo/TODO
- gtk3/sample/gtk-demo/pixbufs.rb
If you look at the line 119, in the C version they use `gdk_pixbuf_new_from_resource` I was not able to create directly a `Gdk::Pixbuf` from a resource so I created a `Gtk::Image` and use the `Gyk::Image#pixbuf` method.
Tell me if think that we should use `Gdk::Pixbuf.new(:resource => path)`
> Gtk3 sample gtk demo pixbufs rb

- goffice/test/run-test.rb
- gsf/test/run-test.rb
- travis-before-script.sh
Follows up #772, #774.
But for now, `gsf` and `goffice` have no test.
Them test will be failure though.
> Enable working tests for gsf and goffice

- Rakefile
I was not able to build the gem files with `rake gem:build` so I modified the main Rakefile. I hope this is the good way to do this.
> Append the gsf, gnm and goffice in the Rakefile

- gobject-introspection/lib/gobject-introspection/loader.rb
I have used the method `rubyish_class_name` in
*    load_object_info
*    load_enum_info
*    load_struct_info
*    define_struct
*    load_flags_info
*    load_interface_info
and  I have added a comment af line 177. There is this function:
```ruby
def define_enum(info)
self.class.define_class(info.gtype,
enum_class_name(info),
@base_module)
end
def enum_class_name(info) # TODO : should be removed? used only in Gtk3 loader
info.name
end
```
The `enum_class_name` is only used in Gtk3, I think that we should replace it with `rubyish_class_name`
> Gi loader rubyish class name

- gdk_pixbuf2/lib/gdk_pixbuf2/pixbuf.rb
- gdk_pixbuf2/test/test-gdk_pixbuf.rb
I hope this is what you expected. Ifollowed the C code in rbgdk-pixbuf.c. All the tests are not done yet but I prefer to be sure that my work correspond to what you asked me.
One question about the inclusion of Gdk_pixbuf2, the only way to make it works was to do something like this : 
```ruby
module Gdk
class Pixbuf < GdkPixbuf::Pixbuf
end
end
```
Is there any "metprogramming" tricks that can try to load from  GdkPixbuf all the non found constants or methods of Gdk like with `method_missing`.
> Gdk pixbuf2 backward compatibility

- gdk_pixbuf2/test/test-pixbuf.rb
@kou just a remainder that I have two pending questions: 
#783 : Is there a way to exclude some structure to be loaded in GI ?
#790 : I don't see how `GLib::Deprecatable` does the same job that the instruction include `GdkPixbuf`.
I don't know if you had seen them, just to be sure.
Thanks.
> Add tests for GdkPixbuf::Pixbuf#new

- gdk_pixbuf2/lib/gdk_pixbuf2/pixbuf.rb
- gdk_pixbuf2/test/test-pixbuf.rb
There is no `initialize_new_from_subpixbuf` but there is `GdkPixbuf::Pixbuf#new_subpixbuf`
> Gdk pixbuf new from subpixbuf test

- gtk3/sample/gtk-demo/pixbufs.rb
I have just updated this one demo with the `GdkPixbuf::Pixbuf` form because the others demos with `Gdk::Pixbuf` were yet not working.
> Use GdkPixbuf form in pixbufs.rb

- poppler/ext/poppler/rbpoppler-page.c
- poppler/test/test_page.rb
Hi.
I used poppler.gem 3.0.8 in Mac OS X 10.10.5, ruby version is 2.2.2 and 2.3.1. And I got segmentation fault when I access several times to the array of PopplerRectangle objects via Page#text_layout.
So I rewrote text_layout method in a simple way. Could you please see my modification and test case?
Thanks.
> Segmentation fault in Poppler::Page#text_layout.

- glib2/ext/glib2/rbglib.c
- glib2/ext/glib2/rbgutil.c
- glib2/ext/glib2/rbgutil.h
If I understand well the ruby/encoding.h has been introduced with ruby 1.9 ~ so you want to remove the if close because you support only ruby version (> 2.1).
I hope it is what you wanted in #782.
> Remove conditionnal macro based on HAVE_RUBY_ENCODING_H

- glib2/ext/glib2/rbgobj_object.c
- glib2/test/test-binding.rb
@kou, 
I had to use the `malloc` function in order to allocate memory for the callback data, of course I have created a function that free the data.
I have tried to use the GClosure version but I was not able to do as I wanted.
Tell me if you want that I change something.
> Glib2 g object bind property full

- gtk3/sample/gtk-demo/main.rb
this prevent to try to run a demo when a user do `main.rb -r a_bad_demo_name`.
> do not try to run a demo when the user provide a bad demo name

- gtk3/sample/gtk-demo/main.rb
When the user use : 
./main.rb -r revealer
Then the related item in the treeView is selected and the user can see the information tab and source tab for the *revealer* demo.
> Gtk3 sample gtk demo main rb set focus on treeview

- Rakefile
- clutter-gdk/COPYING.LIB
- clutter-gdk/README.md
- clutter-gdk/Rakefile
- clutter-gdk/lib/clutter-gdk.rb
- clutter-gdk/lib/clutter-gdk/loader.rb
#943 
I was able to successfully load this lib by adding this line in the `clutter-gtk.rb` file : 
ClutterGdk.init if ClutterGdk.respond_to?(:init)
Then the following test was working : 
```ruby
require "gtk3"
require "clutter-gtk"
ClutterGtk.init
win = Gtk::Window.new(:toplevel)
win.signal_connect("destroy") { Gtk.main_quit }
but = Gtk::Button.new(:label => "click")
but.signal_connect "clicked" do |widget|
stage = ClutterGdk.get_stage_from_window(win.window)
puts stage
end
win.add(but)
win.show_all
win.set_default_size(400, 400)
Gtk.main
```
The only problem I saw was that this line `stage = ClutterGdk.get_stage_from_window(win.window)` returns `nil`. In the same way this  : 
```ruby
puts ClutterGdk.default_display.class #=>  #<Class:0x00000003f54d50>
```
returns an unknown class.
> Clutter gdk

- gtk3/ext/gtk3/rb-gtk3.c
#928
#943
tested with : 
``` ruby
require 'ffi'
module Local
extend FFI::Library
ffi_lib FFI::Library::LIBC
attach_function :setlocale, [:int, :string], :string
end
defs = %w[LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_ALL LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION]
puts "\nbefore GTK3\n"
defs.each_with_index { |d,i| puts "%s: %s\n" % [d,Local.setlocale( i, nil)] }
require 'gtk3'
Gtk::Label.new
puts "\nafter GTK3\n"
defs.each_with_index { |d,i| puts "%s: %s\n" % [d,Local.setlocale( i, nil)] }
```
Results : 
```
ruby test_setlocale_C.rb 
before GTK3
LC_CTYPE: fr_FR.utf8
LC_NUMERIC: C
LC_TIME: C
LC_COLLATE: C
LC_MONETARY: C
LC_MESSAGES: C
LC_ALL: LC_CTYPE=fr_FR.utf8;LC_NUMERIC=C;LC_TIME=C;LC_COLLATE=C;LC_MONETARY=C;LC_MESSAGES=C;LC_PAPER=C …
```
> Force LC_NUMERIC to C when gtk3 is initialized

- .gitignore
Ignore build-time stamps for git, which are created by a extconf.rb / make run.
> Ignore build time-stamps.

- gtk3/sample/gtk-demo/TODO
- gtk3/sample/gtk-demo/popover.rb
- gtk3/sample/gtk-demo/revealer.rb
- gtk3/sample/gtk-demo/search_entry.rb
- gtk3/sample/gtk-demo/search_entry2.rb
- gtk3/sample/gtk-demo/sizegroup.rb
- gtk3/sample/gtk-demo/spinner.rb
- gtk3/sample/gtk-demo/theming_style_classes.rb
- gtk3/sample/gtk-demo/transparent.rb
Just a recap:
*  all the demos already done has been updated to 3.22
*  it remains to adapt the following demos: 
*  application.c 
*  changedisplay.c 
*  combobox.c   
*  css_blendmodes.c	
*  event_axes.c       
*  fishbowl.c	
*  flowbox.c             
*  foreigndrawing  
*  gestures.c        
*  images.c     
*  shortcuts.c     
*  textview.c     
*  toolpalette.c   
*  tree_store.c 
*  the main.rb file must be improved in order to display in the left all the data files (code, informations , ui files or open gl shaders) related to the selected demo.
*  If I well understood, all the gtk3 code after 3.22 will not really change and they start to work on gtk4 (correct me if I am wrong).
> Gtk3 sample gtk demo todo checks part4

- pango/lib/pango/font-description.rb
Without it a call to
Pango::FontDescription.new()
without parameters will fail.
> Add missing braces

- gobject-introspection/test/test-union-info.rb
I don't know any union with `#is_discriminated? == true`. If you know one please tell me, so that I can test all the functions of `GObjectIntrospection::UnionInfo`.
> Improve tests for GObjectIntrospection::UnionInfo

- glib2/ext/glib2/rbgobj_typeinterface.c
- glib2/test/test-typeinterface.rb
This fixes the check that Interface modules do so they can only be included in classes that inherit from `GLib::Instantiatable`.
> Fix check for inheritance from GLib::Instantiatable

- gtk3/sample/gtk-demo/main.rb
Since `GtkPrintOperation` is a very peculiar widget  ( https://developer.gnome.org/gtk3/stable/gtk3-High-level-Printing-API.html) it seems that we can not returns a widget from the demo. So I just disable the font change in the demo selector (`TreeView` on the left of the UI) when the returned value does not have a `signal_connect` method.
> Ensure that there is no crash when the demo does not returns a widget

- gtk3/sample/gtk-demo/css_pixbufs.rb
@kou,
could you try this demo because it generates an error in `lib/gtk3/text-buffer.rb:182` 
It must be related to the GLib::Bytes new api : 
NoMethodError: undefined method `bytesize' for #<GLib::Bytes:0x1ba6458 ptr=0x29fbd60 own=true>
Thanks.
> Update to new api of Pango

- glib2/lib/glib-mkenums.rb
According to [ruby-gnome2 diffoscope](https://tests.reproducible-builds.org/debian/dbd/unstable/armhf/ruby-gnome2_3.1.0-1.diffoscope.html#ruby-gnome--dev_-.-.---_armhf.deb-data.tar.xz-data.tar-.-usr-lib-arm-linux-gnueabihf-ruby-vendor_ruby--.-.--glib-enum-types.h), glib-enum-types.h sometimes generated order ramdomness.
* [glib2/ext/glib2/extconf.rb](https://github.com/ruby-gnome2/ruby-gnome2/blob/3.1.6/glib2/ext/glib2/extconf.rb#L68-L77)
* [glib2/lib/mkmf-gnome2.rb#glib_mkenums](https://github.com/ruby-gnome2/ruby-gnome2/blob/3.1.6/glib2/lib/mkmf-gnome2.rb#L426)
* [glib2/lib/glib-mkenums.rb#GLib::MkEnums.create](https://github.com/ruby-gnome2/ruby-gnome2/blob/3.1.6/glib2/lib/glib-mkenums.rb#L139-L140)
* [glib2/lib/glib-mkenums.rb#GLib::MkEnums.new](https://github.com/ruby-gnome2/ruby-gnom …
> glib-enum-types.h sometimes generated order ramdomness

- gtk2/sample/misc/button2.rb
- gtk3-no-gi/sample/misc/button2.rb
- gtk3/sample/misc/button2.rb
- pango-no-gi/sample/layout.rb
they are still using `/usr/local` as shebang path.
> fix shebang path for examples

- webkit2-gtk/test/test-webkit2-gtk-web-view.rb
In my Debian LXC testbed, this fails randomly.
> extend timeout for some slow environment

- poppler/lib/poppler/document.rb
- poppler/test/poppler-test-utils.rb
- poppler/test/test-annotation.rb
test-annotation is still failing with : 
```
Failure:
<#<Poppler::Annot:0x1436448 ptr=0xd15340>> was expected to be kind_of?
<Poppler::AnnotType> but was
<Poppler::Annot>.
test_type(TestAnnotation)
/home/cedlemo/Projets/Ruby/ruby-gnome2/poppler/test/test-annotation.rb:4:in `test_type'
1: class TestAnnotation < Test::Unit::TestCase
2:   def test_type
3:     only_poppler_version(0, 7, 2)
=> 4:     assert_kind_of(Poppler::AnnotType, annotation)
5:   end
6: 
7:   def test_contents
```
> Poppler test annotation

- vte3/lib/vte3/loader.rb
- vte3/lib/vte3/regex.rb
- vte3/test/test-terminal-regex.rb
@kou,
These Pull Request add support for `Vte::Regex`, the usage of `Glib::Regex` with `Vte::Terminal` is still working (with v = 0.48.3 at least) but is deprecated. (https://developer.gnome.org/vte/0.48/VteRegex.html).
I am sorry for the bad tests, I know that you consider that `assert_instance_of` are useless tests but I did not find anything else to test.
> Vte3 regex

- atk/dependency-check/Rakefile
- clutter-gstreamer/dependency-check/Rakefile
- clutter-gtk/dependency-check/Rakefile
- clutter/dependency-check/Rakefile
- gdk3/dependency-check/Rakefile
- gdk_pixbuf2/dependency-check/Rakefile
- goffice/dependency-check/Rakefile
- gsf/dependency-check/Rakefile
- gtksourceview3/dependency-check/Rakefile
- poppler/dependency-check/Rakefile
- rsvg2/dependency-check/Rakefile
- vte3/dependency-check/Rakefile
- webkit-gtk/dependency-check/Rakefile
- webkit2-gtk/dependency-check/Rakefile
As I wrote on https://github.com/ruby-gnome2/native-package-installer/issues/8 , Red Hat / Fedora package provides pkgconfig(foo) is such package contains foo.pc pkgconfig file. 
So instead of using package (rpm) name directory, using such virtual provides is preferred.
Note: I did not modify gnumeric/dependency-check/Rakefile this time, because this file does not contain ``unless PKGConfig.check_version?("foo")`` (yet?)
> Use pkgconfig(foo) virtual provides for Red Hat based dependency

- gobject-introspection/ext/gobject-introspection/rb-gi-argument.c
I just saw that I made a typo in the branch name -_-' , the macro name is `CSTRFILENAME2RVAL`.
> gi : fix typo in CSTR2FILENAME2RVAL macro

- gtk4/lib/gtk4/loader.rb
- gtk4/lib/gtk4/message-dialog.rb
- gtk4/sample/action-namespace.rb
- gtk4/test/test-gtk-message-dialog.rb
It seems that this is needed when a new `Gtk::Dialog` is created like in the *action-namespace.rb* demo.
Without this I have the following message:
```
/home/cedlemo/Projects/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:317:in `invoke': GtkDialog is not subtype of GtkMessageDialog
from /home/cedlemo/Projects/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:317:in `block (2 levels) in load_constructor_infos'
from /home/cedlemo/Projects/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:328:in `block in load_constructor_infos'
from /home/cedlemo/Projects/Ruby/ruby-gnome2/gtk4/lib/gtk4/dialog.rb:21:in `initialize'
from ./action-namespace.rb:60:in `new'
from ./action-namespace.rb:60:in `block in action'
from …
```
> Gtk4 message dialog

- gtk4/lib/gtk4/loader.rb
- gtk4/test/test-gtk-box.rb
I just kept the rewrite of `Gtk::Box.new` from the Gtk3 file, the API changed for : 
* https://developer.gnome.org/gtk4/3.93/GtkBox.html#gtk-box-set-child-packing
* https://developer.gnome.org/gtk4/3.93/GtkBox.html#gtk-box-pack-start
> Gtk4 : Customize Gtk::Box#new

- gtk3/sample/gtk-demo/demo.gresource.xml
Thank you for your update. 
I checked https://github.com/ruby-gnome2/ruby-gnome2/issues/1184 and found it still did not work.
I add popover-3.18.ui to demo.gresource.xml.
Please check it.
> gtk3 sample: work popover demo with GTK+ 3.18 again

- gdk_pixbuf2/Rakefile
- gdk_pixbuf2/gdk_pixbuf2.gemspec
I push this so that you can see what I did because I am not able to build the *gdk_pixbuf2* : 
```bash
ruby -S rake gem --trace                                                                     ruby-gnome2/gdk_pixbuf2  gdk_pixbuf2_static_gem_spec
** Invoke gem (first_time)
rake aborted!
Don't know how to build task 'ext/gdk_pixbuf2/depend' (see --tasks)
/home/cedlemo/.gem/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task_manager.rb:59:in `[]'
/home/cedlemo/.gem/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:62:in `lookup_prerequisite'
/home/cedlemo/.gem/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:58:in `block in prerequisite_tasks'
/home/cedlemo/.gem/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:58:in `map'
/home/cedlemo/.gem/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:58:in `prerequisite_tasks' …
```
> Gdk pixbuf2 static gem spec

- gobject-introspection/lib/gobject-introspection/loader.rb
Because `n_args` contains arguments of index number of array.
example:
```
/**
* garrow_orc_file_reader_set_field_indexes:
* @reader: A #GArrowORCFileReader.
* @field_indexes: (nullable) (array length=n_field_indexes):
*   The field indexes to be read.
* @n_field_indexes: The number of the specified indexes.
*
* Since: 0.10.0
*/
void
garrow_orc_file_reader_set_field_indexes(GArrowORCFileReader *reader,
const gint *field_indexes,
guint n_field_indexes)
{
....
}
```
`field_indexes` cannot access via `=`.
```
@reader.field_indexes = [1, 3]
`NoMethodError: undefined method `field_indexes=' for #<Arrow::ORCFileReader:0x7faa6d3e5700 ptr=0x7faa6d1d82e0>`
```
This PR fixes it.
> gobject-introspection: Use n_in_args in define_equal_style_setter

- glib2/test/test-source.rb
This is not defined. It was previously empty, but as it happens GLib
2.57.2 started setting default names for its sources. We should instead
test that we can set a name on a source.
See: https://gitlab.gnome.org/GNOME/glib/commit/208a6e815affead7ef8ed86439fcc2bb6a86d56a
> test-source: Don't assert anything about the idle source's initial name

- gobject-introspection/ext/gobject-introspection/rb-gi-argument.c
For example, free the return value of the following functions.
```cpp
/**
* garrow_boolean_array_get_values:
* @array: A #GArrowBooleanArray.
* @length: (out): The number of values.
*
* Returns: (array length=length) (transfer full):
*   The raw boolean values.
*
*   It should be freed with g_free() when no longer needed.
*/
gboolean *
garrow_boolean_array_get_values(GArrowBooleanArray *array,
gint64 *length)
{
auto arrow_array = garrow_array_get_raw(GARROW_ARRAY(array));
auto arrow_boolean_array =
std::static_pointer_cast<arrow::BooleanArray>(arrow_array);
*length = arrow_boolean_array->length();
auto values = static_cast<gboolean *>(g_new(gboolean, *length));
for (gint64 i = 0; i < *length; ++i) {
values[i] = arrow_boolean_array->Value(i);
}
return values;
}
```
```cpp
/**
* …
```
> gobject-introspection: support "free GIArgument(array)[c][gboolean\gint64] everything"

- atk/README.md
- clutter-gdk/README.md
- gdk_pixbuf2/README.md
- gnumeric/README.md
- goffice/README.md
- gsf/README.md
- gtk3/README.md
- gtk4/README.md
- pango/README.md
- poppler/README.md
- rsvg2/README.md
Replace all Ruby-gnome 2 links in README with Ruby-Gnome
> fix links in READMEs ruby-gnome2 -> ruby-gnome

- glib2/lib/glib-mkenums.rb
GLib 2.62.0 introduced some deprecation warnings for macros in gtestutils.h with the commit https://gitlab.gnome.org/GNOME/glib/commit/40ff4759774516b7dff3b07303a98fc1626b2d0e .
This patch makes GLib::MkEnums correctly parse header files in GLib 2.62.0 again.
Fixes https://github.com/ruby-gnome/ruby-gnome/issues/1294
> glib2: fix parser in MkEnums for resent GLib

- gtksourceview4/dependency-check/Rakefile
It is `libgtksourceview-4-dev`, not `libgtksourceview-4.0-dev` as for Debian.
> Add Ubuntu package name for gtksourceview4

- gtk3/sample/misc/cairo-cursor.rb
* Fix a warning
```
cairo-cursor.rb:23:in `<main>': 'Cairo::Surface#to_pixbuf(src_x, src_y, width, height)' style has been deprecated. Use 'Cairo::Surface#to_pixbuf(:src_x => 0, :src_y => 0, :width => width, :height => height)' style.
```
If you prefer the rocket hash style, please fix it.
> gtk3: fix cairo-cursor example

- gtk3/sample/misc/cursor.rb
34afac0 
* Fix incorrect indentation
* Remove needless inspect
b415989
* Use cycle
If you don't like b415989, please omit it.
> gtk3: fix cursor example

- gtk3/sample/misc/eventbox.rb
3000d4e 
* Fix a warning
```
eventbox.rb:34:in `<main>': 'Cairo::Surface#to_pixbuf(src_x, src_y, width, height)' style has been deprecated. Use 'Cairo::Surface#to_pixbuf(:src_x => 0, :src_y => 0, :width => width, :height => height)' style.
```
f6f7d39
* Improve output
* before
* after
If you don't like f6f7d39, please omit it.
> gtk3: fix eventbox example

- gtk3/sample/misc/filechooser.rb
* Remove needless spaces
* Use symbols instead of constants
> gtk3: fix filechooser example

- gtk3/sample/misc/flowbox.rb
8b623c4 
* Remove a needless space
21fbd76 
* Use symbols
If you don't like 21fbd76, please omit it.
> gtk3: fix flowbox example

- gtk3/sample/misc/image.rb
* Remove the unnecessary elements to make it clear how users display the image file with Ruby/Gtk. 
* The two buttons have the same name. This is a bit weird. Maybe we don't need a second button.
* Remove "test". Because this is not a test...
before
after
> gtk3: improve image example

- vte3/lib/vte3/terminal.rb
- vte3/sample/terminal.rb
* Allow spawn to accept no arguments
```ruby
require 'vte3'
terminal = Vte::Terminal.new
terminal.spawn
```
```
5: from /home/kojix2/.rbenv/versions/2.7.0/bin/irb:23:in `<main>'
4: from /home/kojix2/.rbenv/versions/2.7.0/bin/irb:23:in `load'
3: from /home/kojix2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
2: from (irb):20
1: from /home/kojix2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/vte3-3.4.1/lib/vte3/terminal.rb:47:in `spawn'
ArgumentError (wrong number of arguments (given 0, expected 1))
```
* Import an example from vte
> vte3: fix spawn arguments

- gdk_pixbuf2/sample/anim.rb
* Remove a needless space
* Fix Gtk::Image#new arguments
> gdk_pixbuf2: fix anim example

- gdk_pixbuf2/sample/flip.rb
> gdk_pixbuf2: fix flip example

- gdk_pixbuf2/sample/composite.rb
> gdk_pixbuf2: fix composite example

- gdk_pixbuf2/sample/format.rb
* Skip gtk version checking
* Align Columns
> gdk_pixbuf2: fix format example

- gdk_pixbuf2/sample/loader.rb
* Exit the program when you click [x]
> gdk_pixbuf2: fix loader example

- gdk_pixbuf2/sample/rotate.rb
* Skip gtk version checking
* Fix Image#new arguments
> gdk_pixbuf2: fix rotate example

- gdk_pixbuf2/sample/save.rb
* Fix Pixbuf#new arguments
* Remove a needless space
> gdk_pixbuf2: fix save example

- gdk_pixbuf2/sample/scale.rb
> gdk_pixbuf2: fix scale example

- gdk_pixbuf2/sample/simpleanim.rb
* Use 2 space indent
* The *for loop* looks unique. It seems to be evidence that ruby-gnome has a long history, so I left it as it is.
* Fix Gtk::Image#new argument
> gdk_pixbuf2: fix simpleanim example

- goffice/dependency-check/Rakefile
- gtk3/sample/misc/cairo-cursor.rb
- gtk3/sample/misc/calendar.rb
Fix Ruby-gnome2 -> Ruby-Gnome
I searched for files that used both Ruby-Gnome and Ruby-Gnome2.
```
grep "Ruby-GNOME " -rl | xargs grep "Ruby-GNOME2" -rl
```
And found 4 files. 
* gtk3/sample/misc/cairo-cursor.rb  :confused:
* gtk3/sample/misc/calendar.rb  :confused:
* goffice/dependency-check/Rakefile :new:
* glib2/ext/glib2/rbglib.c (No need to fix)
Fixed.
> Fix Ruby-Gnome2 -> Ruby-Gnome

- gdk_pixbuf2/sample/utils.rb
* Clears the pixbuf and fill the color
* before
* after
* Fix Image#new arguments
> gdk_pixbuf2: fix utils example

- gdk_pixbuf2/sample/xpm.rb
* Use single quotes
* Any other string in this file use single quotes
* Show that there is no interpolation
> gdk_pixbuf2: fix xpm example

- gtk3/sample/misc/recentchooserdialog.rb
* Use symbols instead of constants
* minor change
> gtk3: fix recentchooserdialog example

- rsvg2/sample/svg-viewer.rb
* Use `draw` signal instead of `expose_event`
* Change the order of the lines to make them easier to understand
> rsvg2: fix svg-viewr example

- cairo-gobject/test/run-test.rb
* ~~Update copyright year in README~~
#1359
```
ruby test/run-test.rb 
```
```
Started
..........................
Finished in 0.02428763 seconds.
---------------------------------------------------------
26 tests, 26 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
---------------------------------------------------------
1070.50 tests/s, 1070.50 assertions/s
```
> cairo-gobject: ruby_gnome2_base -> ruby_gnome_base

- clutter/test/run-test.rb
* ~~Update copyright year in README~~
#1359
```
ruby-gnome/clutter$ ruby test/run-test.rb 
```
```
Started
................................................................................
........
Finished in 0.01592881 seconds.
--------------------------------------------------------------------------------
88 tests, 92 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------
5524.58 tests/s, 5775.70 assertions/s
```
> clutter: ruby_gnome2_base -> ruby_gnome_base

- clutter-gstreamer/test/run-test.rb
```
clutter-gstreamer$ ruby test/run-test.rb 
```
```
Started
.O
================================================================================
/home/kojix2/Ruby/ruby-gnome/clutter-gstreamer/test/clutter-gstreamer-test-utils.rb:30:in `only_older_clutter_gstreamer_version'
Omission: Require Clutter-GStreamer < 3.0.0 [test_texture(ClutterGstVideoSinkTest)]
================================================================================
....
Finished in 0.113136679 seconds.
--------------------------------------------------------------------------------
6 tests, 5 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
---------------------------------------------------------------------------- …
```
> clutter-gstreamer: ruby_gnome2_base -> ruby_gnome_base

- clutter-gtk/test/run-test.rb
```
clutter-gtk$ ruby test/run-test.rb 
```
```
Started
.
Finished in 0.001119663 seconds.
-----------------------------------------------------------------------------------------------------------
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-----------------------------------------------------------------------------------------------------------
893.13 tests/s, 893.13 assertions/s
```
> clutter-gtk: ruby_gnome2_base -> ruby_gnome_base

- gdk4/test/run-test.rb
NOTE: I haven't installed and tried gdk4 yet. This pull request is intended to make the same changes as other Ruby-Gnome packages. Thanks.
> gdk4: ruby_gnome2_base -> ruby_gnome_base

- gnumeric/test/run-test.rb
```
gnumeric$ ruby test/run-test.rb
```
```
GLib-GObject-CRITICAL **: Object class GOFontSel doesn't implement property 'level' from interface 'GtkFontChooser'
from /home/kojix2/Ruby/ruby-gnome/gobject-introspection/lib/gobject-introspection/loader.rb:216:in `load_object_info'
from /home/kojix2/Ruby/ruby-gnome/gobject-introspection/lib/gobject-introspection/loader.rb:68:in `load_info'
from /home/kojix2/Ruby/ruby-gnome/goffice/lib/goffice/loader.rb:62:in `load_info'
from /home/kojix2/Ruby/ruby-gnome/gobject-introspection/lib/gobject-introspection/loader.rb:43:in `block in load'
from /home/kojix2/Ruby/ruby-gnome/gobject-introspection/lib/gobject-introspection/repository.rb:34:in `block (2 levels) in each'
from …
```
> gnumeric: ruby_gnome2_base -> ruby_gnome_base

- goffice/test/run-test.rb
```
goffice$ ruby test/run-test.rb 
```
```
GLib-GObject-CRITICAL **: Object class GOFontSel doesn't implement property 'level' from interface 'GtkFontChooser'
from /home/kojix2/Ruby/ruby-gnome/gobject-introspection/lib/gobject-introspection/loader.rb:216:in `load_object_info'
from /home/kojix2/Ruby/ruby-gnome/gobject-introspection/lib/gobject-introspection/loader.rb:68:in `load_info'
from /home/kojix2/Ruby/ruby-gnome/goffice/lib/goffice/loader.rb:62:in `load_info'
from /home/kojix2/Ruby/ruby-gnome/gobject-introspection/lib/gobject-introspection/loader.rb:43:in `block in load'
from /home/kojix2/Ruby/ruby-gnome/gobject-introspection/lib/gobject-introspection/repository.rb:34:in `block (2 levels) in each'
from …
```
> goffice: ruby_gnome2_base -> ruby_gnome_base

- gtk3/test/run-test.rb
```
gtk3$ ruby test/run-test.rb
```
```
Started
............................................................................................................................
............................................................................................................................
...........................
(run-test.rb:29578): Gtk-WARNING **: 12:13:55.829: Style property "nonexistent" is not registered
.................................................................................................
........................
(run-test.rb:29578): Gtk-WARNING **: 12:13:56.030: Could not find signal handler 'on_move_cursor'.  Did you compile with -rdynamic?
.
(run-test.rb:29578): Gtk-WARNING **: 12:13:56.032: …
```
> gtk3: ruby_gnome2_base -> ruby_gnome_base

- gtk4/sample/utils.rb
- gtk4/test/run-test.rb
NOTE: I haven't installed and tried gtk4 yet. This pull request is intended to make the same changes as other Ruby-Gnome packages. Thanks.
> gtk4: ruby_gnome2_base -> ruby_gnome_base

- libsecret/test/run-test.rb
```
libsecret$ ruby test/run-test.rb 
```
```
Omit because libsecret is old
```
Umm :confused: 
It seems that libsecret must be compiled from source. (Ubuntu 19.10)
> libsecret: ruby_gnome2_base -> ruby_gnome_base

- webkit-gtk/test/run-test.rb
```
installing 'libwebkitgtk-3.0-dev' native package... failed
```
Umm :confused: 
It seems that libwebkitgtk must be compiled from source. (Ubuntu 19.10)
> webkit-gtk: ruby_gnome2_base -> ruby_gnome_base

- webkit-gtk2/test/run-test.rb
```
Omit because typelib file doesn't exist: Typelib file for namespace 'WebKit', version '1.0' not found
```
Umm :confused: 
It seems that libwebkitgtk must be compiled from source. (Ubuntu 19.10)
> webkit-gtk2: ruby_gnome2_base -> ruby_gnome_base

- webkit2-gtk/test/run-test.rb
```
webkit2-gtk$ ruby test/run-test.rb 
```
```
Started
..[2020-02-23 16:49:53] INFO  WEBrick 1.6.0
[2020-02-23 16:49:53] INFO  ruby 2.7.0 (2019-12-25) [x86_64-linux]
[2020-02-23 16:49:53] INFO  WEBrick::HTTPServer#start: pid=17678 port=38161
127.0.0.1 - - [23/Feb/2020:16:49:53 JST] "GET / HTTP/1.1" 200 5
- -> /
[2020-02-23 16:49:53] INFO  going to shutdown ...
[2020-02-23 16:49:54] INFO  WEBrick::HTTPServer#start done.
.......
Finished in 1.399719818 seconds.
9 tests, 9 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed …
```
> webkit2-gtk: ruby_gnome2_base -> ruby_gnome_base

- rsvg2/sample/svg-viewer.rb
Fixes usage of deprecated method Gdk window "size" in svg-viewer example.
> rsvg: fix usage of deprecated GDK Window size to width, height

- Gemfile
> Use File.exist? instead of File.exists?

- README.md
* Remove unused TravisCI badges
* Move the badge position to below the title
I considered adding a badge for Github Actions.
There are three separate badges for Linux, Mac, and Windows.
If it were my personal project, I would add the badges. 
But in the case of ruby-gnome, I can't decide if I should add badges. 
If there are too many badges, it doesn't look elegant.
I don't care about the badge itself, 
but seeing a badge that has stopped working is not a good feeling.
Thank you very much.
> Removed unused travicCI badge

- pango/pango.gemspec
While trying to figure out where pango's sourcecode was, by looking at https://rubygems.org/gems/pango/ I just couldn't. This adds extra links to the rubygems metadata that will populate rubygems with those.
I've also defined minimum supported ruby version (as per current changelog it seems we support `>=2.6` only).
You can learn more about the rubygem specification bits I've modified here: https://guides.rubygems.org/specification-reference/
> Fix pango metadata

- gobject-introspection/lib/gobject-introspection/loader.rb
- gobject-introspection/test/test-loader.rb
自身の直接のスーパークラスのvfuncは実装できる一方、それより上の祖先クラスが持つvfuncは実装することができませんでした。
これは `VirtualFunctionImplementable#implement_virtual_function` の戻り値が常に真になっていることが原因と見られたため、直前の行の呼び出しが本来返したい結果であると推測して修正しました。
> gi: fix a bug that virtual functions of grandparent class can't be implemented

- gdk4/dependency-check/Rakefile
pkgconfig id for gdk4 is the same as gtk4
https://koji.fedoraproject.org/koji/rpminfo?fileStart=350&rpmID=27692196#filelist
> Fix pkgconfig id for gdk4

- rsvg2/README.md
- Fixed broken link by pointing it to the [GNOME/librsvg repository](https://github.com/GNOME/librsvg)
> Updated link to librsvg

- gstreamer/sample/audio-example.rb
* Use [pipeline_clock](https://github.com/GStreamer/gstreamer/blob/2db3ddaa9d8e9e0a1659d7e48623c512dbda691b/subprojects/gstreamer/tests/examples/controller/audio-example.c#L30)
```ruby
bin.clock              # => nil
bin.pipelie_clock      # => Gst::SystemClock
```
* Use warn instead of $stderr.puts
* If you do not like this change, undo and merge.
> Fix audio-example

- vte3/lib/vte3/terminal.rb
With Ruby-GNOME using introspection data from GLib 2.70.4, then using the original `Vte::Terminal feed_child` method aliased as `feed_child_raw`, the `feed_child_raw` method was not accepting two args.
When `Vte::Terminal#feed_child_raw` was called with one arg, a string, then it would send the string to the Pty
> Args patch for Vte::Terminal#feed_child

- .gitignore
- Rakefile
The changeset in this pull request will add documentation tasks to the Rakefile
- Task `gem:docs` as presented with `rake -T`, using both of the following tasks
- Task `gem:girdocs` for documentation using yard-gobject-introspection
- Task `gem:rubydocs` for other Ruby docs, using yard
Documentation files will be produced in subdirectories under ./yard_docs/
- in `yard_docs/gir/` for docs using yard-gobject-introspection
- in `yard_docs/ruby/` for Ruby docs using yard
`./yard_docs/` will be removed under the `clean` Rakefile task
`.gitignore` is updated for files created by yard
In commentary: 
Perhaps these Rakefile tasks may serve as any utility for local access to the Ruby-GNOME documentation. This would not be integrated with the documentation tasks for GitHub Actions in Ruby-GNOME. …
> Documentation tasks for Rakefile

- Gemfile
Within the scope of a **Gemfile** evaluated by bundler, the object referenced as `self` may usually be an object of a type **Bundler::Dsl**
Using the `eval_gemfile` method on the **Bundler::Dsl** instance when evaluating an existing `Gemfile.local`, Bundler will then use a **Bundler::Dsl** syntax for the file. This may also ensure that the filename is added to any Gemfile state data for the **Bundler::Dsl** instance
With this patch, a call to the '**gem**' method in a `Gemfile.local` may then be interpreted by bundler as it being a reference to the '**gem**' method on the **Bundler::Dsl** instance. This may differ to how a call to the 'gem' method would be evaluated in ordinary eval.
e.g using `Gemfile.local` to ensure that an interactive Ruby interpreter of any local preference is …
> evaluating local_gemfile using Bundler DSL

- glib2/ext/glib2/rbgobj_type.c
Ruby requires all TypedData objects to have a wrap_struct_name. If it's null then ObjectSpace.dump_all will crash when it tries to read it.
> Always set wrap_struct_name for rbgobj

- glib2/ext/glib2/rbgobj_type.c
TypedData objects requires the free function to also manage the allocated data buffer. Since rbgobj is always created with TypedData_Make_Struct, we have to also free the buffer to not leak memory.
> Fix memory leak in rbgobj

- gtk4/sample/examples/action-namespace.rb
- gtk4/sample/examples/drawing.rb
- gtk4/sample/examples/grid_packing.rb
This fixes a few deprecation warnings and some errors in the drawing example. The `frame` has [been removed](https://gitlab.gnome.org/GNOME/gtk/-/commit/ece9e7e240bd91fc788343f0b6a9be3ccc52f81c) in the C example, so I removed it as well.
> gtk4: Fix errors and deprecations in sample example files

- gtk4/sample/examples/application1/exampleapp.rb
- gtk4/sample/examples/application3/README.md
- gtk4/sample/examples/application3/exampleapp.rb
The gtk4/sample/examples/application3 directory is based on the C
programs in the following directory in the GTK 4 repository.
- https://gitlab.gnome.org/GNOME/gtk/-/blob/main/examples/application3
File opening codes and stack object are added to the `exampleapp.rb` in the aplication3 directory.
> gtk4: add sample/examples/application3

- gtk4/sample/examples/application4/README.md
- gtk4/sample/examples/application4/exampleapp.rb
The original C program uses `gtk_action_map_add_action_entries` function.
- https://gitlab.gnome.org/GNOME/gtk/-/blob/main/examples/application4
But the program in this directory uses Ruby `each` iteration instead of the function above.
It makes the program simple and easy to understand.
> gtk4: Add sample/examples/application4

- gtk4/sample/getting-started/README.md
- gtk4/test/test-gtk-builder.rb
Fixing typos with [typos-cli](https://github.com/crate-ci/typos)
> gtk4: fix typos

- gstreamer/lib/gst.rb
- gstreamer/lib/gst/audio-loader.rb
- gstreamer/test/test-audio.rb
Hi,
I added `Gst::AudioLoader` to use [`GstAudioInfo`](https://gstreamer.freedesktop.org/documentation/audio/audio-info.html?gi-language=c) for #1634
Thank you.
> gstreamer: Add AudioLoader

- gtksourceview5/sample/test.rb
This example was listed under gtksourceview5, but it used gtksourceview4.  I updated it to use gtk4/gtksourceview5.
This file should be renamed to gtksourceview5_demo.rb.  
Also, please look at my recent open issue about ColumnView, and please push the most recent gtk3 gem that has the pixbuf issue in Windows fixed.
Thanks for all your great work,
Eric
> gtksourceview5 sample: use gtksourceview5
